Removed create stylesheets and added a custom theme
mark-yacoub/metremenqeemi pull request #53
Opened 2022-02-21 20:22 UTC by markusamuel

2022-03-02 00:24 UTC, mark-yacoub requested changes
you seem to have broken soomething with yarn.lock aw 7aga. 
when i pull your branch and `yarn`, i get this
```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

compared with `neeb` in so many ways and it's def only on your branch

2022-03-02 00:24 UTC, mark-yacoub commented on android/settings.gradle
> +include ':react-native-vector-icons'
did u test on android?

2022-03-02 00:24 UTC, mark-yacoub commented on ios/Podfile
> +  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
did u test on ios?

2022-03-02 00:24 UTC, mark-yacoub commented on package.json
> +    "react-native-cli": "^2.0.1",
why

2022-03-02 00:24 UTC, mark-yacoub commented on package.json
> +    "react-native-vector-icons": "^9.1.0",
where is this used?

2022-03-02 00:24 UTC, mark-yacoub commented on src/App.js
> +
remove space

2022-03-02 00:24 UTC, mark-yacoub commented on src/App.js
> +  fontSize: 18,
order them alphabetically

2022-03-02 00:24 UTC, mark-yacoub commented on src/screens/LessonsList.js
> +    <View style={{flex: 1}}>
isn't RN `flex:1` by default?

2022-03-02 00:24 UTC, mark-yacoub commented on src/screens/level1/learningLetters.js
> +    <SafeAreaView style={{flex: 1}}>
ditto

2022-03-07 01:22 UTC, closed without merging

2022-03-07 01:58 UTC, markusamuel commented on src/screens/LessonsList.js
> +    <View style={{flex: 1}}>
Good catch