Replaced stylesheets with theme provider and added a seperator to the lessons list
mark-yacoub/metremenqeemi pull request #57
Opened 2022-03-07 02:10 UTC by markusamuel

2022-03-07 16:39 UTC, mark-yacoub requested changes
please watch oout for ALL warnings and errors. I see this when i run `yarn`
<img width="853" alt="image" src="https://user-images.githubusercontent.com/11547193/157077647-61a519de-619f-48b2-9fcd-cdb7705899e2.png">

2022-03-07 16:44 UTC, mark-yacoub commented on src/screens/level1/learningLetters.js
> -import {View, Text, TextInput, SafeAreaView, ScrollView, StyleSheet, StatusBar} from 'react-native';
n5alni balna ya bro - seems untested:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/11547193/157078624-b7229150-5152-4c7f-bf4c-bdd6550d4d85.png">

2022-03-12 15:01 UTC, markusamuel commented on src/screens/level1/learningLetters.js
> -import {View, Text, TextInput, SafeAreaView, ScrollView, StyleSheet, StatusBar} from 'react-native';
good catch @mark - commit amended

2022-03-12 15:01 UTC, merged

2022-03-12 18:25 UTC, mark-yacoub commented
you should not have merged if you hadn't received an approval.

2022-03-12 18:28 UTC, markusamuel commented
best practise or something gone wrong ?



On Sat, Mar 12, 2022 at 1:25 PM Mark Yacoub ***@***.***>
wrote:

> you should not have merged if you hadn't received an approval.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mark-yacoub/metremenqeemi/pull/57#issuecomment-1065936422>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AE64ELSHEJBFBC3FUJZG2Q3U7TOSRANCNFSM5QB6Y7GA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>